/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2019-03-08 11:18:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.awt.event.WindowStateListener;
import java.awt.Window;
import java.sql.*;
import java.util.List;

public final class display_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>删除成绩</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("thead, tr {\r\n");
      out.write("border-top-width: 1px;\r\n");
      out.write("border-top-style: solid;\r\n");
      out.write("border-top-color: #a8bfde;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("border-bottom-width: 1px;\r\n");
      out.write("border-bottom-style: solid;\r\n");
      out.write("border-bottom-color: #a8bfde;\r\n");
      out.write("}\r\n");
      out.write("td,th {\r\n");
      out.write("padding: 5px 10px;\r\n");
      out.write("font-size: 12px;\r\n");
      out.write("font-family: Verdana;\r\n");
      out.write("color: #5b7da3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr{\r\n");
      out.write("background: #d3dfed\r\n");
      out.write("}tr{\r\n");
      out.write("background: #FFF\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body background=\"image/4.jpg\">\r\n");
      out.write("<center>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"display_1.jsp\" method=post>\r\n");
      out.write("\t\t<input type=\"submit\" name=\"a\" value=\"显示所有学生信息\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
 
	String number=null;
	String name=null;
	String classes=null;
	String term=null;
	float math,english,sql,java,test,total;
	Connection con=(Connection)session.getAttribute("con");
	ResultSet rs=(ResultSet)session.getAttribute("rs");
	
	out.print("<br>");
	out.print("<br>");
	out.print("<Table>");
	out.print("<TR>");
	out.print("<TH width=100>"+"学号"+"</th>");
	out.print("<TH width=100>"+"姓名"+"</th>");
	out.print("<TH width=100>"+"班级"+"</th>");
	out.print("<TH width=100>"+"数学"+"</th>");
	out.print("<TH width=100>"+"数据库"+"</th>");
	out.print("<TH width=100>"+"英语"+"</th>");
	out.print("<TH width=100>"+"JAVA"+"</th>");
	out.print("<TH width=100>"+"软件测试"+"</th>");
	out.print("<TH width=100>"+"学期"+"</th>");
	out.print("<TH width=100>"+"总分"+"</th>");
	out.print("</TR>");
	if(rs!=null){
		
		while(rs.next()){
			out.print("<TR>");
			number=rs.getString(1);
			name=rs.getString(2);
			classes=rs.getString(3);
			math=rs.getInt(4);
			sql=rs.getInt(5);
			english=rs.getInt(6);
			java=rs.getInt(7);
			test=rs.getInt(8);
			term=rs.getString(9);
			total=math+sql+sql+english+java+test;
			out.print("<TD align='center'>"+number+"</TD>");
			out.print("<TD align='center'>"+name+"</TD>");
			out.print("<TD align='center'>"+classes+"</TD>");
			out.print("<TD align='center'>"+math+"</TD>");
			out.print("<TD align='center'>"+sql+"</TD>");
			out.print("<TD align='center'>"+english+"</TD>");
			out.print("<TD align='center'>"+java+"</TD>");
			out.print("<TD align='center'>"+test+"</TD>");
			out.print("<TD align='center'>"+term+"</TD>");
			out.print("<TD align='center'>"+total+"</TD>");
			out.print("</TR>");
		}
		
	}
	
	out.print("</Table>");
	
      out.write("\r\n");
      out.write("\t</font>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function datacheck(){\r\n");
      out.write("\tvar form=document.getElementById(\"form\");\r\n");
      out.write("\tif(delform.number.value==\"\"){\r\n");
      out.write("\t\twindow.alert(\"您必须输入学号!\");\r\n");
      out.write("\t\tdocument.getElementById(\"numberId\").focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
