/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2019-03-08 11:21:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Menu_005f2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>成绩管理</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("html, body{\r\n");
      out.write("   padding:0px;\r\n");
      out.write("   margin:0px;\r\n");
      out.write("   font-family: 'Raleway', sans-serif;\r\n");
      out.write("   color:#FFF;\r\n");
      out.write("   height:100%;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("   background:#8ECDF0; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container{\r\n");
      out.write("   max-width:200px;\r\n");
      out.write("   background:#7A7A7A;\r\n");
      out.write("   margin:40px auto;\r\n");
      out.write("   padding:10px 0px 20px 0px;\r\n");
      out.write("   border:1px solid #111;\r\n");
      out.write("   border-radius:4px;\r\n");
      out.write("   box-shadow:0px 4px 5px rgba(0, 0, 0, 0.75);\r\n");
      out.write("}\r\n");
      out.write(".link{\r\n");
      out.write("   font-size:16px;\r\n");
      out.write("   font-weight:300;\r\n");
      out.write("   text-align:center;\r\n");
      out.write("   position:relative;\r\n");
      out.write("   height:40px;\r\n");
      out.write("   line-height:40px;\r\n");
      out.write("   margin-top:10px;\r\n");
      out.write("   overflow:hidden;\r\n");
      out.write("   width:90%;\r\n");
      out.write("   margin-left:5%;\r\n");
      out.write("   cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(".link:after{\r\n");
      out.write("   content: '';\r\n");
      out.write("   position:absolute;\r\n");
      out.write("   width:80%;\r\n");
      out.write("   border-bottom:1px solid rgba(255, 255, 255, 0.5);\r\n");
      out.write("   bottom:50%;\r\n");
      out.write("   left:-100%;\r\n");
      out.write("   transition-delay: all 0.5s;\r\n");
      out.write("   transition: all 0.5s;\r\n");
      out.write("}\r\n");
      out.write(".link:hover:after,\r\n");
      out.write(".link.hover:after{\r\n");
      out.write("   left:100%;\r\n");
      out.write("}\r\n");
      out.write(".link .text{\r\n");
      out.write("   text-shadow:0px -40px 0px rgba(255, 255, 255, 1);\r\n");
      out.write("   transition:all 0.75s;\r\n");
      out.write("   transform:translateY(100%) translateZ(0);\r\n");
      out.write("   transition-delay:all 0.25s;\r\n");
      out.write("}\r\n");
      out.write(".link:hover .text,\r\n");
      out.write(".link.hover .text{\r\n");
      out.write("   text-shadow:0px -40px 0px rgba(255, 255, 255, 0);\r\n");
      out.write("   transform:translateY(0%) translateZ(0) scale(1.1);\r\n");
      out.write("   font-weight:600;\r\n");
      out.write("}\r\n");
      out.write("a{text-decoration:none}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"link\">\r\n");
      out.write("    <div class=\"text\"><a href=\"query_1_1.jsp\" target=\"mainFrame\">成绩查询</a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"link\">\r\n");
      out.write("    <div class=\"text\"><a href=\"StuUpdate.jsp\" target=\"mainFrame\">信息修改</a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var links = document.getElementsByClassName('link')\r\n");
      out.write("for(var i = 0; i <= links.length; i++)\r\n");
      out.write("   addClass(i)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function addClass(id){\r\n");
      out.write("   setTimeout(function(){\r\n");
      out.write("      if(id > 0) links[id-1].classList.remove('hover')\r\n");
      out.write("      links[id].classList.add('hover')\r\n");
      out.write("   }, id*750) \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align:center;margin:50px 0; font:normal 14px/24px 'MicroSoft YaHei';\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
